# Generated by Django 5.0.1 on 2024-01-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exams_answers_id_remove_exams_question_id_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='exam_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.exams'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='exam_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.exams'),
        ),
    ]
