# Generated by Django 5.0.1 on 2024-01-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exams_answers_id_remove_exams_question_id_and_more'),
        ('subjects', '0002_questions_exam_id_subjects_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams'),
        ),
    ]
