# Generated by Django 5.0.1 on 2024-01-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_questions_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='exam_id',
        ),
    ]
