# Generated by Django 5.0.1 on 2024-01-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exams_question_id_alter_exams_time_limit'),
        ('subjects', '0005_questions_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams'),
        ),
    ]
