# Generated by Django 5.0.1 on 2024-01-22 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_remove_questions_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subjects'),
        ),
    ]
