# Generated by Django 5.0.1 on 2024-01-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_alter_questions_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects'),
        ),
    ]
