# Generated by Django 5.0.1 on 2024-01-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_exams_subject_delete_selectquestion'),
        ('subjects', '0009_alter_questions_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='exam_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.exams'),
        ),
    ]
