# Generated by Django 5.0.1 on 2024-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
