# Generated by Django 5.0.1 on 2024-01-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exams_answers_id_remove_exams_question_id_and_more'),
        ('subjects', '0004_remove_questions_exam_id_remove_subjects_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='question_id',
            field=models.ManyToManyField(to='subjects.questions'),
        ),
    ]
