# Generated by Django 5.0.1 on 2024-01-22 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exams_question_id_alter_exams_time_limit'),
        ('subjects', '0007_remove_questions_exam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exams')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.questions')),
            ],
        ),
    ]
