# Generated by Django 5.0.1 on 2024-01-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_selectquestion'),
        ('subjects', '0007_remove_questions_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects'),
        ),
    ]
