# Generated by Django 5.0.1 on 2024-01-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exams_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='subject',
        ),
        migrations.DeleteModel(
            name='SelectQuestion',
        ),
    ]
